### ISSUE TITLE
如何下载预训练的模型

### ISSUE THREAD

**Issue by xiaodin1** [foamliu/Joint-Estimation-of-Age-and-Gender#1]
运行python demo.py提示FileNotFoundError: [Errno 2] No such file or directory: 'data/imdb-gender-age101.pkl'，请问下我通过link下载的是BEST_checkpoint_.pth.tar这个文件，请问怎么使用呢？

**Comment by watertianyi** [comment]
我下载的这个文件打不开，请问作者是怎么解决的呢

**Comment by herobacking** [comment]
这是一个加密压缩文件，需要有密码的

**Comment by foamliu** [comment]
不需要解压缩，也没有密码，直接执行 demo.py，自己会加载。

**Comment by AadeIT** [comment]
@xiaodin1 ，您解决这个问题了吗？我放入模型之后运行还是会报这样的错误，而pkl我又不知道去哪里下载

**Comment by zlh004** [comment]
下载的tar文件是损坏的，打不开。直接运行demo也是报错 
@foamliu 
请问您是怎么解决的
