### ISSUE TITLE
你好， 您这个项目缺少必要的data文件夹吧，文件家中需要pickle文件等，无法直接运行demo.py

### ISSUE THREAD

**Issue by herobacking** [foamliu/Joint-Estimation-of-Age-and-Gender#3]
你好， 您这个项目缺少必要的data文件夹吧，文件家中需要pickle文件等，无法直接运行demo.py

**Comment by Hemingwaycn** [comment]
win和linux下均无法解压这个tar包，不知是否是我这边的问题
https://github.com/foamliu/Age-and-Gender/releases/download/1.0/BEST_checkpoint_.pth.tar

**Comment by foamliu** [comment]
不需要解压的，下载了直接用。执行demo.py 就行。

**Comment by AadeIT** [comment]
@herobacking ，您好我也是这个问题，请问您解决了吗？

**Comment by zlh004** [comment]
我也是打不开，demo直接运行出错

**Comment by zlh004** [comment]
想说一下，几乎所有人都出现了相同的问题，想麻烦您能看一下。
您说的直接执行demo.py也是存在问题，所以想请您能再帮我们想一想解决办法
@foamliu 
多有冒犯，请您见谅
