### ISSUE TITLE
预处理

### ISSUE THREAD

**Issue by zlh004** [foamliu/Joint-Estimation-of-Age-and-Gender#6]
请问楼主，预处理过后，imdb-gender-age101.pkl这个文件只有47字节，请问这是正常的么？

**Comment by zlh004** [comment]
调试了一下，发现预处理程序当中is_valid这个值一直为false。

**Comment by zlh004** [comment]
请问楼主，为什么执行到下面这句话
weights = np.load('src/weights/pnet.npy')[()]
返回值就为空呢，然后就导致代码try失败

**Comment by TowerPro** [comment]
请问解决了吗？

**Comment by TowerPro** [comment]
> 请问楼主，预处理过后，imdb-gender-age101.pkl这个文件只有47字节，请问这是正常的么？

请问解决了吗？
